# site settings
title: Pratyay Jaidev
subtitle:
email: pratyay.jaidev@gmail.com
description: Focused, driven, people-oriented.
baseurl: "" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: National University of Singapore
city: Kent Ridge
country: Singapore
phone: Drop me an e-mail!

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url: https://github.com/pratyayj
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url: https://www.linkedin.com/in/pratyayj
pinterest_url:
slack_url:
twitter_url:
medium_url: https://medium.com/@pratyay.jaidev

# build settings
markdown: kramdown

sass:
  style: compressed
